### ISSUE TITLE
About installation and dependencies

### ISSUE THREAD

**Issue by kerkelae** [quin-med-harvard-edu/pyGRASP#1]
As a part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/4865), I would like to suggest an important improvement in the `README` file. As far as I can tell, the repository does not contain an installable Python package, but a collection of scripts instead. I found a [conda environment file](https://github.com/quin-med-harvard-edu/pyGRASP/blob/main/requirements.yml) that I assume lists all the software requirements for running the scripts. Is the code meant to be run by cloning the repository, installing the requirements, and running the scripts? If so, I think that it would be important to add a description of these steps in the `README` file.

**Comment by curtcorum** [comment]
I second the above comment.

**Comment by cariyurek** [comment]
Thank you for pointing this issue @kerkelae. I have realized that we have mentioned to use the environment file for the Docker but forgot to do so for running the scripts. We will add this description as suggested.

**Comment by cariyurek** [comment]
I have added steps to run the demo using the data provided in [figshare](https://figshare.com/articles/dataset/DCE_MRI_MRU_dat/20465637) to the demos section in readme.md. I have tried to run the demo from the scratch by cloning the repository and installing the environment. I have realized that requirements.yml file had some missing packages and [environment.yml](https://github.com/quin-med-harvard-edu/pyGRASP/blob/main/environment.yml) was the complete one, so I removed the requirements.yml file. 

Please let me know if you have any trouble running the demo.

**Comment by kerkelae** [comment]
Hi @cariyurek, I am unable to run the demo:

```
(dce_env) leevi@leevi-laptop:~/Desktop/joss-review/pyGRASP$ bash pyGRASP_demo.sh 
  0%|                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]pymapVBVD version 0.4.1
Software version: VD
Scan 1/2, read all mdhs: 57.0MB [00:00, 350MB/s]                                                                                                                                                                   
Scan 1/2, read all mdhs:  73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 41.8M/57.0M [00:00<00:00, 438MB/s/home/leevi/anaconda3/envs/dce_env/lib/python3.7/site-packages/mapvbvd/twix_map_obj.py:755: RuntimeWarning: invalid value encountered in add█████████████████████████████████▉ | 11.2G/11.3G [00:11<00:00, 2.12GB/s]
  raw = (raw[:, 0] + 1j * raw[:, 1]).reshape(readShape, order='F')                                                                                                         | 9342/111384 [00:07<01:15, 1354.21it/s]
                                                                                                                                                                                                                  pyGRASP_demo.sh: line 5: 53012 Killed                  "$env_path"/dce_env/bin/python3.7"" "$code_path"/convert_raw_to_dataset.py"" -i "$inputOutput_path"/MRU.csv"" -pg "$code_path"/parameters/grasp_params.json"" -pp "$code_path"/parameters/p_proc_params.json"" -o $inputOutput_path -fr True -fc True -nspkc 500                                                                                                                
Traceback (most recent call last):
  File "/home/leevi/Desktop/joss-review/pyGRASP/demo_reconstruction.py", line 70, in <module>
    crl_msu_dat = CRLMRUData(root_csv_file, type_parse='slice')
  File "/home/leevi/Desktop/joss-review/pyGRASP/data_loader/crl_dataset.py", line 21, in __init__
    with open(self.csv_root, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/leevi/Desktop/joss-review/inputOutput/loader.csv'
Traceback (most recent call last):
  File "/home/leevi/Desktop/joss-review/pyGRASP/slice_to_vol.py", line 76, in <module>
    for rec_file in os.listdir(folder_raw_rec):
FileNotFoundError: [Errno 2] No such file or directory: '/home/leevi/Desktop/joss-review/inputOutput/../sub-1/*/raw-rec/'
```
Do you know what may be causing this?

**Comment by cariyurek** [comment]
Hi, @kerkelae ,

I am sorry to hear that. I tried to replicate the error but I could not. 

You are getting an error when data is read. I suspect that pymapvbvd does not have the correct version installed. Could you run "conda list" and send me the output? 

Also, could you be sure that your environment is pointed correctly?

**Comment by kerkelae** [comment]
Below is the contents of `pyGRASP_demo.sh`:

```
env_path="/home/leevi/anaconda3/envs"
code_path="/home/leevi/Desktop/joss-review/pyGRASP"
inputOutput_path="/home/leevi/Desktop/joss-review/inputOutput"

"$env_path"/dce_env/bin/python3.7"" "$code_path"/convert_raw_to_dataset.py"" -i "$inputOutput_path"/MRU.csv"" -pg "$code_path"/parameters/grasp_params.json"" -pp "$code_path"/parameters/p_proc_params.json"" -o $inputOutput_path -fr True -fc True -nspkc 500

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$env_path"/dce_env/lib""

"$env_path"/dce_env/bin/python3.7"" "$code_path"/demo_reconstruction.py"" -p "$code_path"/parameters/grasp_params.json"" -d "$inputOutput_path"/loader.csv"" -o . -sid sub-1

"$env_path"/dce_env/bin/python3.7"" "$code_path"/slice_to_vol.py"" -p "$code_path"/parameters/p_proc_params.json"" -d "$inputOutput_path"/../sub-1/*/raw-rec/"" -o "$inputOutput_path"/../sub-1/""
```
And below is what `conda list` gives: 
```
# packages in environment at /home/leevi/anaconda3/envs/dce_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
attrdict                  2.0.1                      py_0    conda-forge
attrs                     20.3.0                   pypi_0    pypi
backcall                  0.2.0                      py_0    anaconda
blas                      1.0                         mkl    anaconda
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.26           h06a4308_2    anaconda
cached-property           1.5.2                      py_0    anaconda
certifi                   2021.10.8        py37h06a4308_0    anaconda
charset-normalizer        2.0.8                    pypi_0    pypi
chart-studio              1.1.0                    pypi_0    pypi
cloudpickle               1.6.0                      py_0    anaconda
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py37h5e8e339_3    conda-forge
dask-core                 2.30.0                     py_0    anaconda
dataclasses               0.6                      pypi_0    pypi
dbus                      1.13.18              hb2f20db_0    anaconda
decorator                 4.4.2                      py_0    anaconda
expat                     2.2.10               he6710b0_2    anaconda
fontconfig                2.13.0               h9420a91_0    anaconda
freetype                  2.10.4               h5ab3b9f_0    anaconda
glib                      2.56.2               hd408876_0    anaconda
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
h5py                      3.1.0                    pypi_0    pypi
hdf5storage               0.1.18                   pypi_0    pypi
icu                       58.2                 he6710b0_3    anaconda
idna                      3.3                      pypi_0    pypi
imagecodecs-lite          2019.12.3        py37h902c9e0_3    conda-forge
imageio                   2.9.0                      py_0    anaconda
importlib-metadata        3.10.0                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2020.2                      254    anaconda
ipykernel                 5.3.4            py37h5ca1d4c_0    anaconda
ipython                   7.18.1           py37h5ca1d4c_0    anaconda
ipython_genutils          0.2.0                    py37_0    anaconda
jedi                      0.17.2                   py37_0    anaconda
joblib                    0.17.0                     py_0    anaconda
jpeg                      9b                   habf39ab_1    anaconda
jupyter_client            6.1.7                      py_0    anaconda
jupyter_core              4.6.3                    py37_0    anaconda
kiwisolver                1.3.1            py37hc928c03_0    conda-forge
lcms2                     2.11                 h396b838_0    anaconda
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.2.1             hf484d3e_1007    anaconda
libgcc                    7.2.0                h69d50b8_2    anaconda
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libgomp                   9.3.0               h2828fa1_18    conda-forge
libpng                    1.6.37               hbc83047_0    anaconda
libsodium                 1.0.18               h7b6447c_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.1.0                h2733197_1    anaconda
libuuid                   1.0.3                h1bed415_2    anaconda
libxcb                    1.14                 h7b6447c_0    anaconda
libxml2                   2.9.10               hb55368b_3    anaconda
lz4-c                     1.9.2                heb0550a_3    anaconda
matplotlib                3.3.2                    pypi_0    pypi
mkl                       2020.2                      256    anaconda
mkl-service               2.3.0            py37h8f50634_2    conda-forge
mkl_fft                   1.2.0            py37h161383b_1    conda-forge
mkl_random                1.2.0            py37h9fdb41a_1    conda-forge
ncurses                   6.2                  he6710b0_1    anaconda
networkx                  2.5                        py_0    anaconda
nibabel                   3.2.1                    pypi_0    pypi
numpy                     1.19.2           py37h54aff64_0  
numpy-base                1.19.2           py37hfa32c7d_0  
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1l               h7f8727e_0    anaconda
packaging                 20.9                     pypi_0    pypi
pandas                    1.0.1                    pypi_0    pypi
parso                     0.7.0                      py_0    anaconda
patsy                     0.5.2                    pypi_0    pypi
pcre                      8.44                 he6710b0_0    anaconda
pexpect                   4.8.0                    py37_1    anaconda
pickleshare               0.7.5                 py37_1001    anaconda
pillow                    8.2.0            py37he98fc37_0    anaconda
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
plotly                    5.4.0                    pypi_0    pypi
pluggy                    0.13.1                   pypi_0    pypi
prompt-toolkit            3.0.8                      py_0    anaconda
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.6.0                    py37_0    anaconda
py                        1.10.0                   pypi_0    pypi
pygments                  2.7.1                      py_0    anaconda
pymapvbvd                 0.4.1                    pypi_0    pypi
pynrrd                    0.4.2                    pypi_0    pypi
pynufft                   2021.0.1                 pypi_0    pypi
pyparsing                 2.4.7                      py_0    anaconda
pyqt                      5.9.2            py37hcca6a23_4    conda-forge
pytest                    6.2.3                    pypi_0    pypi
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.1              pyhd3eb1b0_0    anaconda
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd3eb1b0_0    anaconda
pywavelets                1.1.1            py37h902c9e0_3    conda-forge
pyyaml                    5.4.1            py37h5e8e339_0    conda-forge
pyzmq                     19.0.2           py37he6710b0_1    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
readline                  7.0                  h7b6447c_5    anaconda
requests                  2.26.0                   pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
scikit-image              0.18.2                   pypi_0    pypi
scikit-learn              0.24.1                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                49.6.0           py37h89c1867_3    conda-forge
simpleitk                 2.0.2                    pypi_0    pypi
sip                       4.19.8          py37hf484d3e_1000    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h62c20be_0    anaconda
statsmodels               0.13.1                   pypi_0    pypi
tenacity                  8.0.1                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0    anaconda
tifffile                  2020.6.3                   py_0    conda-forge
tk                        8.6.10               hbc83047_0    anaconda
toml                      0.10.2                   pypi_0    pypi
toolz                     0.11.1                     py_0    anaconda
torch                     1.8.1                    pypi_0    pypi
torchkbnufft              1.1.0                    pypi_0    pypi
tornado                   6.1              py37h5e8e339_1    conda-forge
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    anaconda
transforms3d              0.3.1                h2e23829_0    owlas
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.7                   pypi_0    pypi
wcwidth                   0.2.5                      py_0    anaconda
webcolors                 1.11.1                   pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0    anaconda
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xz                        5.2.5                h7b6447c_0    anaconda
yaml                      0.2.5                h7b6447c_0    anaconda
zeromq                    4.3.3                he6710b0_3    anaconda
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.4                h0b5b093_3    anaconda
```

**Comment by cariyurek** [comment]
Hi @kerkelae ,

Your environment list seems correct. 

Could you delete everything in the folder "inputOutput_path" except MRU.csv. and just run the data reader part:

env_path="/home/leevi/anaconda3/envs"
code_path="/home/leevi/Desktop/joss-review/pyGRASP"
inputOutput_path="/home/leevi/Desktop/joss-review/inputOutput"

"$env_path"/dce_env/bin/python3.7"" "$code_path"/convert_raw_to_dataset.py"" -i "$inputOutput_path"/MRU.csv"" -pg "$code_path"/parameters/grasp_params.json"" -pp "$code_path"/parameters/p_proc_params.json"" -o $inputOutput_path -fr True -fc True -nspkc 500

You can comment or delete the rest of pyGRASP_demo.sh for now just to debug this part. And could you send me the error? 

Sorry for the inconvenience again.

**Comment by cariyurek** [comment]
Hi @kerkelae ,

I was able to replicate the problem you are having on a laptop with 16GB RAM. I think you are having memory issues. We have been running pyGRASP in servers with at least 128GB RAM. It would be great if you could try to run pyGRASP on a server with a large memory. In addition, we will provide another test data (smaller in size) after de-identifying and trying to run pyGRASP on the laptop again. I will post here when we upload the new data to figshare. We are sorry for this issue.

**Comment by kerkelae** [comment]
Good that you were able to figure out the cause of the problem! Please let me know when the new dataset is available. I would like to be able to conduct this review using my personal computer with 32 GB of RAM. It'd also be great if you implemented a feature to let the user know when the software fails due to insufficient memory.

**Comment by cariyurek** [comment]
Hi @kerkelae ,

We have provided another data that is 3 times smaller in size in [figshare](https://figshare.com/articles/dataset/DCE-MRI_raw_data/22043195) and updated demo steps in our GitHub accordingly. The new data has less number of channel measurements and poorer in quality, so you will not end up with good quality DCE-MR images as in Figure 2 in the paper. Unfortunately, I was not able to run it on a laptop with 16GB RAM. Maybe it would be possible for you to run it on your personal computer with 32 GB of RAM. Now, it prints out the data size, available memory and warning about monitoring insufficient memory. 

If this does not work we may have to collect some data (not DCE-MRI but with the same MRI sequence and less number of channels) very small in size for you to run the demo.  

I hope this works.
